///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

/*
emX-U8 - generated GUI code
Copyright (C) 2025-2026 GamingWithEvets Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include <wx/font.h>
#include <wx/sizer.h>

#include "about.h"

bool AboutDialogBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
        return false;

    auto* sizer = new wxBoxSizer(wxVERTICAL);

    auto* head = new wxStaticText(this, wxID_ANY, _("emX-U8"), wxDefaultPosition, wxDefaultSize,
        wxALIGN_CENTER_HORIZONTAL);
    {
        wxFont font(wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT));
        font.SetWeight(wxFONTWEIGHT_BOLD);
        head->SetFont(font);
    }
    sizer->Add(head, wxSizerFlags().Center());

    auto* desc = new wxStaticText(this, wxID_ANY, _("Yet another ROHM nX-U8/100 emulator\n"));
    sizer->Add(desc, wxSizerFlags().Center());

    m_version = new wxStaticText(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize,
        wxALIGN_CENTER_HORIZONTAL);
    sizer->Add(m_version, wxSizerFlags().Center());

    license = new wxHtmlWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxHW_NO_SELECTION);
    license->SetPage(
    _("<p style=\"text-align: center;\">\n<b>Credits</b>\n<ul>\n<li><b>telecomadm1145</b> - Binary serializer</li>\n<li><b>LBPHacker</b> and <b>Xyzstk</b> - Clock generator, timer, time base counter logic</li>\n</ul><br><br>\n\nPart of this project was developed with assistance from artificial intelligence (AI).<br><br>\n\nThis program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.<br><br>\nThis program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.<br><br>\nYou should have received a copy of the GNU General Public License along with this program. If not, see <a href=\"https://www.gnu.org/licenses/\">https://www.gnu.org/licenses/</a>.\n</p>"));
    sizer->Add(license, wxSizerFlags(1).Center().Expand());

    m_btn = new wxButton(this, wxID_ANY, _("OK"));
    m_btn->SetDefault();
    sizer->Add(m_btn, wxSizerFlags().Center());

    SetSizer(sizer);
    Centre(wxBOTH);

    // Event handlers
    m_btn->Bind(wxEVT_BUTTON,
        [this](wxCommandEvent&)
        {
            EndModal(0);
        });
    license->Bind(wxEVT_HTML_LINK_CLICKED,
        [this](wxHtmlLinkEvent& event)
        {
            wxLaunchDefaultBrowser(event.GetLinkInfo().GetHref());
        });

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
