///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/button.h>
#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/gdicmn.h>
#include <wx/html/htmlwin.h>
#include <wx/intl.h>
#include <wx/stattext.h>

class AboutDialogBase : public wxDialog
{
public:
    wxStaticText* m_version;

    AboutDialogBase() {}
    AboutDialogBase(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = _("About emX-U8"),
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500, 500),
        long style = wxDEFAULT_DIALOG_STYLE|wxMINIMIZE_BOX, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = _("About emX-U8"),
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500, 500),
        long style = wxDEFAULT_DIALOG_STYLE|wxMINIMIZE_BOX, const wxString &name = wxDialogNameStr);

protected:

    // Class member variables

    wxButton* m_btn;
    wxHtmlWindow* license;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
