///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/button.h>
#include <wx/checkbox.h>
#include <wx/event.h>
#include <wx/font.h>
#include <wx/gdicmn.h>
#include <wx/intl.h>
#include <wx/panel.h>
#include <wx/radiobut.h>
#include <wx/textctrl.h>

class RegCheckBox;
class RegTextCtrl;

class BrkpointPanelBase : public wxPanel
{
public:
    wxButton* m_btn_delete;

    BrkpointPanelBase() {}
    BrkpointPanelBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL, const wxString &name = wxPanelNameStr)
    {
        Create(parent, id, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL, const wxString &name = wxPanelNameStr);

protected:

    // Virtual event handlers -- override them in your derived class

    virtual void OnRadioType0(wxCommandEvent& event) { event.Skip(); }
    virtual void OnRadioType1(wxCommandEvent& event) { event.Skip(); }
    virtual void OnRadioType2(wxCommandEvent& event) { event.Skip(); }

    // Class member variables

    RegCheckBox* m_enabled;
    RegTextCtrl* m_csr;
    RegTextCtrl* m_pc;
    wxRadioButton* m_radio_type0;
    wxRadioButton* m_radio_type1;
    wxRadioButton* m_radio_type2;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
