///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

/*
emX-U8 - generated GUI code
Copyright (C) 2025 GamingWithEvets Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include <wx/font.h>
#include <wx/stattext.h>

#include "brkpoint.h"

bool BrkpointBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, ConvertDialogToPixels(size), style, name))
        return false;

    m_sizer = new wxBoxSizer(wxVERTICAL);
    m_sizer->SetMinSize(800, 600);

    auto* head = new wxStaticText(this, wxID_ANY, _("Breakpoint list"));
    {
        wxFont font(wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT));
        font.SetWeight(wxFONTWEIGHT_BOLD);
        head->SetFont(font);
    }
    m_sizer->Add(head, wxSizerFlags().Center().Border(wxALL));

    auto* button_sizer = new wxBoxSizer(wxHORIZONTAL);

    m_btn_add = new wxButton(this, wxID_ANY, _("Add breakpoint"));
    button_sizer->Add(m_btn_add, wxSizerFlags().Border(wxALL));

    m_btn_clear = new wxButton(this, wxID_ANY, _("Delete all"));
    button_sizer->Add(m_btn_clear, wxSizerFlags().Border(wxALL));

    m_sizer->Add(button_sizer, wxSizerFlags().Center().Border(wxALL));

    SetSizerAndFit(m_sizer);
    Centre(wxBOTH);

    // Event handlers
    m_btn_add->Bind(wxEVT_BUTTON, &BrkpointBase::OnBtnAdd, this);
    m_btn_clear->Bind(wxEVT_BUTTON, &BrkpointBase::OnBtnClear, this);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
