///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

/*
emX-U8 - generated GUI code
Copyright (C) 2025-2026 GamingWithEvets Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include <wx/sizer.h>
#include <wx/stattext.h>

#include "regcheckbox.h"
#include "regtextctrl.h"

#include "brkpoint_panel.h"

bool BrkpointPanelBase::Create(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size,
    long style, const wxString& name)
{

    if (!wxPanel::Create(parent, id, pos, size, style, name))
        return false;

    auto* box_sizer = new wxBoxSizer(wxHORIZONTAL);
    box_sizer->SetMinSize(800, -1);

    m_enabled = new RegCheckBox(this, wxID_ANY, wxEmptyString);
    m_enabled->SetValue(true);
    box_sizer->Add(m_enabled, wxSizerFlags().Center().Border(wxALL));

    auto* csrpc_sizer = new wxBoxSizer(wxHORIZONTAL);

    m_csr = new RegTextCtrl({false, 1}, this, wxID_ANY, wxEmptyString);
    m_csr->SetMinSize(ConvertDialogToPixels(wxSize(15, -1)));
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_csr->SetFont(wxFont(font_info));
    }
    csrpc_sizer->Add(m_csr, wxSizerFlags());

    auto* csrpc_sep = new wxStaticText(this, wxID_ANY, _(" : "));
    csrpc_sizer->Add(csrpc_sep, wxSizerFlags().Center());

    m_pc = new RegTextCtrl({true, 4}, this, wxID_ANY, wxEmptyString);
    m_pc->SetMinSize(ConvertDialogToPixels(wxSize(25, -1)));
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_pc->SetFont(wxFont(font_info));
    }
    csrpc_sizer->Add(m_pc, wxSizerFlags());

    box_sizer->Add(csrpc_sizer, wxSizerFlags().Border(wxALL));

    box_sizer->AddStretchSpacer(1);

    auto* type_sizer = new wxBoxSizer(wxHORIZONTAL);

    m_radio_type1 = new wxRadioButton(this, wxID_ANY, _("Read"), wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
    m_radio_type1->Enable(false);
    type_sizer->Add(m_radio_type1, wxSizerFlags().Center());

    m_radio_type2 = new wxRadioButton(this, wxID_ANY, _("Write"));
    m_radio_type2->Enable(false);
    type_sizer->Add(m_radio_type2, wxSizerFlags().Center());

    m_radio_type0 = new wxRadioButton(this, wxID_ANY, _("Execute"));
    m_radio_type0->SetValue(true);
    type_sizer->Add(m_radio_type0, wxSizerFlags().Center());

    box_sizer->Add(type_sizer, wxSizerFlags().Center().Border(wxALL));

    box_sizer->AddSpacer(10);

    m_btn_delete = new wxButton(this, wxID_ANY, _(" X "), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    box_sizer->Add(m_btn_delete, wxSizerFlags().Border(wxALL));

    SetSizerAndFit(box_sizer);

    // Event handlers
    m_radio_type0->Bind(wxEVT_RADIOBUTTON, &BrkpointPanelBase::OnRadioType0, this);
    m_radio_type1->Bind(wxEVT_RADIOBUTTON, &BrkpointPanelBase::OnRadioType1, this);
    m_radio_type2->Bind(wxEVT_RADIOBUTTON, &BrkpointPanelBase::OnRadioType2, this);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
