///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/button.h>
#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/gdicmn.h>
#include <wx/intl.h>
#include <wx/sizer.h>

class BrkpointBase : public wxDialog
{
public:
    BrkpointBase() {}
    BrkpointBase(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = _("Breakpoint Manager"),
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxDIALOG_NO_PARENT|wxMINIMIZE_BOX, const wxString &name =
        wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = _("Breakpoint Manager"),
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxDIALOG_NO_PARENT|wxMINIMIZE_BOX, const wxString &name =
        wxDialogNameStr);

protected:

    // Virtual event handlers -- override them in your derived class

    virtual void OnBtnAdd(wxCommandEvent& event) { event.Skip(); }
    virtual void OnBtnClear(wxCommandEvent& event) { event.Skip(); }

    // Class member variables

    wxBoxSizer* m_sizer;
    wxButton* m_btn_add;
    wxButton* m_btn_clear;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
