///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

/*
emX-U8 - generated GUI code
Copyright (C) 2025 GamingWithEvets Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include <wx/colour.h>
#include <wx/settings.h>
#include <wx/stattext.h>

#include "regcheckbox.h"
#include "regtextctrl.h"

#include "debugger.h"

bool DebuggerBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, ConvertDialogToPixels(size), style, name))
        return false;

    auto* box_sizer = new wxBoxSizer(wxHORIZONTAL);

    auto* col0_sizer = new wxBoxSizer(wxVERTICAL);

    auto* disas_sizer = new wxBoxSizer(wxVERTICAL);
    disas_sizer->SetMinSize(800, 300);

    auto* disas_head = new wxStaticText(this, wxID_ANY, _("Disassembly"));
    {
        wxFont font(wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT));
        font.SetWeight(wxFONTWEIGHT_BOLD);
        disas_head->SetFont(font);
    }
    disas_sizer->Add(disas_head, wxSizerFlags().Center());

    m_disas = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize,
        wxTE_MULTILINE|wxTE_READONLY|wxTE_NO_VSCROLL);
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_disas->SetFont(wxFont(font_info));
    }
    disas_sizer->Add(m_disas, wxSizerFlags(1).Expand());

    col0_sizer->Add(disas_sizer, wxSizerFlags().Expand().Border(wxALL));

    auto* regs_sizer = new wxBoxSizer(wxVERTICAL);
    regs_sizer->SetMinSize(800, 300);

    auto* stepbuttons_sizer = new wxBoxSizer(wxHORIZONTAL);

    m_btn_run = new wxButton(this, wxID_ANY, _("Run [F9]"));
    m_btn_run->Enable(false);
    stepbuttons_sizer->Add(m_btn_run, wxSizerFlags());

    m_btn_stepinto = new wxButton(this, wxID_ANY, _("Step Into [F7]"));
    m_btn_stepinto->Enable(false);
    stepbuttons_sizer->Add(m_btn_stepinto, wxSizerFlags());

    m_btn_stepover = new wxButton(this, wxID_ANY, _("Step Over [F8]"));
    m_btn_stepover->Enable(false);
    stepbuttons_sizer->Add(m_btn_stepover, wxSizerFlags());

    regs_sizer->Add(stepbuttons_sizer, wxSizerFlags().Center().Border(wxALL));

    m_r_sizer = new wxBoxSizer(wxHORIZONTAL);

    regs_sizer->Add(m_r_sizer, wxSizerFlags().Center().Expand().Border(wxALL));

    auto* sde_sizer = new wxBoxSizer(wxHORIZONTAL);

    sde_sizer->AddStretchSpacer(1);

    auto* csrpc_sizer = new wxBoxSizer(wxHORIZONTAL);

    auto* csrpc_text = new wxStaticText(this, wxID_ANY, _("CSR:PC  "));
    csrpc_sizer->Add(csrpc_text, wxSizerFlags().Center());

    m_csr = new RegTextCtrl({false, 1}, this, wxID_ANY, wxEmptyString);
    m_csr->Enable(false);
    m_csr->SetMinSize(ConvertDialogToPixels(wxSize(10, -1)));
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_csr->SetFont(wxFont(font_info));
    }
    csrpc_sizer->Add(m_csr, wxSizerFlags());

    auto* csrpc_sep = new wxStaticText(this, wxID_ANY, _(" : "));
    csrpc_sizer->Add(csrpc_sep, wxSizerFlags().Center());

    m_pc = new RegTextCtrl({true, 4}, this, wxID_ANY, wxEmptyString);
    m_pc->Enable(false);
    m_pc->SetMinSize(ConvertDialogToPixels(wxSize(25, -1)));
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_pc->SetFont(wxFont(font_info));
    }
    csrpc_sizer->Add(m_pc, wxSizerFlags());

    sde_sizer->Add(csrpc_sizer, wxSizerFlags().Border(wxALL));

    auto* sp_sizer = new wxBoxSizer(wxHORIZONTAL);

    auto* sp_text = new wxStaticText(this, wxID_ANY, _("SP  "));
    sp_sizer->Add(sp_text, wxSizerFlags().Center());

    m_sp = new RegTextCtrl({false, 4}, this, wxID_ANY, wxEmptyString);
    m_sp->Enable(false);
    m_sp->SetMinSize(ConvertDialogToPixels(wxSize(25, -1)));
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_sp->SetFont(wxFont(font_info));
    }
    sp_sizer->Add(m_sp, wxSizerFlags());

    sde_sizer->Add(sp_sizer, wxSizerFlags().Border(wxALL));

    auto* dsr_sizer = new wxBoxSizer(wxHORIZONTAL);

    auto* dsr_text = new wxStaticText(this, wxID_ANY, _("DSR  "));
    dsr_sizer->Add(dsr_text, wxSizerFlags().Center());

    m_dsr = new RegTextCtrl(this, wxID_ANY, wxEmptyString);
    m_dsr->Enable(false);
    m_dsr->SetMinSize(ConvertDialogToPixels(wxSize(15, -1)));
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_dsr->SetFont(wxFont(font_info));
    }
    dsr_sizer->Add(m_dsr, wxSizerFlags());

    sde_sizer->Add(dsr_sizer, wxSizerFlags().Border(wxALL));

    auto* ea_sizer = new wxBoxSizer(wxHORIZONTAL);

    auto* ea_text = new wxStaticText(this, wxID_ANY, _("EA  "));
    ea_sizer->Add(ea_text, wxSizerFlags().Center());

    m_ea = new RegTextCtrl({false, 4}, this, wxID_ANY, wxEmptyString);
    m_ea->Enable(false);
    m_ea->SetMinSize(ConvertDialogToPixels(wxSize(25, -1)));
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_ea->SetFont(wxFont(font_info));
    }
    ea_sizer->Add(m_ea, wxSizerFlags());

    sde_sizer->Add(ea_sizer, wxSizerFlags().Border(wxALL));

    sde_sizer->AddStretchSpacer(1);

    regs_sizer->Add(sde_sizer, wxSizerFlags().Expand().Border(wxALL));

    m_next_dsr = new RegCheckBox(this, wxID_ANY, _("Use the current value of DSR in the next instruction"));
    m_next_dsr->Enable(false);
    regs_sizer->Add(m_next_dsr, wxSizerFlags().Center().Border(wxALL));

    auto* psw_sizer = new wxBoxSizer(wxHORIZONTAL);

    psw_sizer->AddStretchSpacer(1);

    auto* psw_text = new wxStaticText(this, wxID_ANY, _("PSW  "));
    psw_sizer->Add(psw_text, wxSizerFlags().Center());

    m_psw = new RegTextCtrl(this, wxID_ANY, wxEmptyString);
    m_psw->Enable(false);
    m_psw->SetMinSize(ConvertDialogToPixels(wxSize(15, -1)));
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_psw->SetFont(wxFont(font_info));
    }
    psw_sizer->Add(m_psw, wxSizerFlags().Center());

    auto* psw_flags_sizer = new wxBoxSizer(wxHORIZONTAL);

    m_psw_c = new RegCheckBox(this, wxID_ANY, _("C"));
    m_psw_c->Enable(false);
    psw_flags_sizer->Add(m_psw_c, wxSizerFlags().Center());

    m_psw_z = new RegCheckBox(this, wxID_ANY, _("Z"));
    m_psw_z->Enable(false);
    psw_flags_sizer->Add(m_psw_z, wxSizerFlags().Center());

    m_psw_s = new RegCheckBox(this, wxID_ANY, _("S"));
    m_psw_s->Enable(false);
    psw_flags_sizer->Add(m_psw_s, wxSizerFlags().Center());

    m_psw_ov = new RegCheckBox(this, wxID_ANY, _("OV"));
    m_psw_ov->Enable(false);
    psw_flags_sizer->Add(m_psw_ov, wxSizerFlags().Center());

    m_psw_mie = new RegCheckBox(this, wxID_ANY, _("MIE"));
    m_psw_mie->Enable(false);
    psw_flags_sizer->Add(m_psw_mie, wxSizerFlags().Center());

    m_psw_hc = new RegCheckBox(this, wxID_ANY, _("HC"));
    m_psw_hc->Enable(false);
    psw_flags_sizer->Add(m_psw_hc, wxSizerFlags().Center());

    m_psw_elevel = new RegTextCtrl({false, 1, true}, this, wxID_ANY, wxEmptyString);
    m_psw_elevel->Enable(false);
    m_psw_elevel->SetMinSize(ConvertDialogToPixels(wxSize(10, -1)));
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_psw_elevel->SetFont(wxFont(font_info));
    }
    psw_flags_sizer->Add(m_psw_elevel, wxSizerFlags().Center());

    auto* psw_elevel_text = new wxStaticText(this, wxID_ANY, _("  ELEVEL"));
    psw_flags_sizer->Add(psw_elevel_text, wxSizerFlags().Center());

    psw_sizer->Add(psw_flags_sizer, wxSizerFlags().Border(wxALL));

    psw_sizer->AddStretchSpacer(1);

    regs_sizer->Add(psw_sizer, wxSizerFlags().Expand().Border(wxALL));

    m_lr_sizer = new wxBoxSizer(wxHORIZONTAL);

    regs_sizer->Add(m_lr_sizer, wxSizerFlags().Center().Expand().Border(wxALL));

    m_epsw_sizer = new wxBoxSizer(wxHORIZONTAL);

    regs_sizer->Add(m_epsw_sizer, wxSizerFlags().Center().Expand().Border(wxALL));

    col0_sizer->Add(regs_sizer, wxSizerFlags().Expand().Border(wxALL));

    box_sizer->Add(col0_sizer, wxSizerFlags().Border(wxALL));

    auto* col1_sizer = new wxBoxSizer(wxVERTICAL);

    auto* call_sizer = new wxBoxSizer(wxVERTICAL);
    call_sizer->SetMinSize(400, 300);

    auto* call_head = new wxStaticText(this, wxID_ANY, _("Call stack"), wxDefaultPosition, wxDefaultSize,
        wxALIGN_CENTER_HORIZONTAL);
    {
        wxFont font(wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT));
        font.SetWeight(wxFONTWEIGHT_BOLD);
        call_head->SetFont(font);
    }
    call_sizer->Add(call_head, wxSizerFlags().Center());

    auto* call_sub = new wxStaticText(this, wxID_ANY, _("(Note: May differ from real stack data!)"),
        wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    {
        wxFont font(wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT));
        font.SetStyle(wxFONTSTYLE_ITALIC);
        call_sub->SetFont(font);
    }
    call_sizer->Add(call_sub, wxSizerFlags().Center());

    m_call_stack = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize,
        wxTE_MULTILINE|wxTE_READONLY);
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_call_stack->SetFont(wxFont(font_info));
    }
    call_sizer->Add(m_call_stack, wxSizerFlags(1).Expand());

    col1_sizer->Add(call_sizer, wxSizerFlags().Expand().Border(wxALL));

    auto* stack_sizer = new wxBoxSizer(wxVERTICAL);
    stack_sizer->SetMinSize(400, 300);

    auto* stack_text = new wxStaticText(this, wxID_ANY, _("Raw stack data"));
    {
        wxFont font(wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT));
        font.SetWeight(wxFONTWEIGHT_BOLD);
        stack_text->SetFont(font);
    }
    stack_sizer->Add(stack_text, wxSizerFlags().Center().Border(wxALL));

    auto* stack_head = new wxStaticText(this, wxID_ANY, _("#     Address  Value   Bytes  Source"));
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_MODERN).Weight(wxFONTWEIGHT_BOLD);
        stack_head->SetFont(wxFont(font_info));
    }
    stack_head->SetForegroundColour(wxColour(_("#0000FF")));
    stack_sizer->Add(stack_head, wxSizerFlags().Border(wxLEFT, FromDIP(wxSize(4, -1)).x));

    m_stack_raw = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize,
        wxTE_MULTILINE|wxTE_READONLY);
    {
        wxFontInfo font_info(10);
        font_info.Family(wxFONTFAMILY_TELETYPE);
        m_stack_raw->SetFont(wxFont(font_info));
    }
    stack_sizer->Add(m_stack_raw, wxSizerFlags(1).Expand());

    col1_sizer->Add(stack_sizer, wxSizerFlags().Expand().Border(wxALL));

    box_sizer->Add(col1_sizer, wxSizerFlags().Border(wxALL));

    SetSizerAndFit(box_sizer);
    Centre(wxBOTH);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
