///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/button.h>
#include <wx/checkbox.h>
#include <wx/dialog.h>
#include <wx/font.h>
#include <wx/gdicmn.h>
#include <wx/intl.h>
#include <wx/sizer.h>
#include <wx/textctrl.h>

class RegCheckBox;
class RegTextCtrl;

class DebuggerBase : public wxDialog
{
public:
    wxButton* m_btn_run;
    wxButton* m_btn_stepinto;
    wxButton* m_btn_stepover;

    DebuggerBase() {}
    DebuggerBase(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = _("Debugger"),
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxDIALOG_NO_PARENT|wxMINIMIZE_BOX, const wxString &name =
        wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = _("Debugger"),
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxDIALOG_NO_PARENT|wxMINIMIZE_BOX, const wxString &name =
        wxDialogNameStr);

protected:

    // Class member variables

    RegCheckBox* m_next_dsr;
    RegCheckBox* m_psw_c;
    RegCheckBox* m_psw_hc;
    RegCheckBox* m_psw_mie;
    RegCheckBox* m_psw_ov;
    RegCheckBox* m_psw_s;
    RegCheckBox* m_psw_z;
    RegTextCtrl* m_csr;
    RegTextCtrl* m_dsr;
    RegTextCtrl* m_ea;
    RegTextCtrl* m_pc;
    RegTextCtrl* m_psw;
    RegTextCtrl* m_psw_elevel;
    RegTextCtrl* m_sp;
    wxBoxSizer* m_epsw_sizer;
    wxBoxSizer* m_lr_sizer;
    wxBoxSizer* m_r_sizer;
    wxTextCtrl* m_call_stack;
    wxTextCtrl* m_disas;
    wxTextCtrl* m_stack_raw;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
